name: adv_async_widget_example
description: Example project for adv_async_widget
publish_to: 'none'
version: 1.0.0+1
author: oznecniV97
homepage: https://github.com/oznecniV97/adv_async_widget

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  adv_async_widget:
    path: ../

  flutter:
    sdk: flutter

flutter:
