name: adv_async_widget
description: Are you tired of always writing the same future and stream builders? Use AdvAsyncWidget to write only the code that you need for!
version: 0.0.2
homepage: https://github.com/oznecniV97/adv_async_widget

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
