name: adv_async_widget
description: Utility widgets for standard future and stream uses
version: 0.0.1
homepage: https://github.com/oznecniV97/adv_async_widget

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
