name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    name: 'Publish to pub.dev'
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3
      # Setup Dart SDK with JWT token
      - uses: dart-lang/setup-dart@v1.5.0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: "stable"
      # Minimal package setup and dry run checks.
      - name: Install dependencies
        run: flutter pub get
      - name: Publish - dry run
        run: flutter pub publish --dry-run
      # Publishing...
      - name: Publish to pub.dev
        run: flutter pub publish -f